import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const data = `
  .accordion-btn {background-color: #ADD8E6;color: #444;cursor: pointer;padding: 18px;width: 100%;border: none;text-align: left;outline: none;font-size: 15px;transition: 0.4s;}.container {padding: 0 18px;display: none;background-color: white;overflow: hidden;}h1 {word-spacing: 5px;color: blue;font-weight: bold;text-align: center;}`;

  return (
    <html lang="en">
    <head>
        <meta charSet="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        {/*<link rel="stylesheet" href="/_next/static/css/app/layout.css" data-n-g="" media="print" onLoad="this.media='all'" />*/}
        {/*<noscript>*/}
        {/*<link rel="stylesheet" href="/_next/static/css/app/layout.css"/>*/}
        {/*</noscript>*/}
      {/*<link rel="preload" href="/_next/static/css/app/layout.css" as="style" onLoad="this.onload=null;this.rel='stylesheet'" />*/}
      {/*<noscript><link rel="stylesheet" href="/_next/static/css/app/layout.css"/></noscript>*/}
      <style type={'text/css'} dangerouslySetInnerHTML={{ __html: data }} />
    </head>
    <body>
    {children}
    </body>
    </html>
  )
}
